### ISSUE TITLE
Sub method call in ERB template to use double quotes

### ISSUE THREAD

**Issue by kercsoj** [skatkov/yard-markdown#16]
The sub method call in the `templates/default/fulldoc/markdown/setup.rb` uses single quotes. This is wrong, instead of 

`**Defined in:** <%= object.file ? object.file.sub(Dir.pwd, '') : "(unknown)" %>`

it should be

`**Defined in:** <%= object.file ? object.file.sub(Dir.pwd, "") : "(unknown)" %>`

Otherwise the generation fails.

**Comment by kercsoj** [comment]
Here is a proposal on how to fix it: https://github.com/skatkov/yard-markdown/pull/17

**Comment by skatkov** [comment]
Great!

Thanks for contributing and a follow up fix.
